/*
 * Milestone B1 — cross-language challenge agreement.
 *
 *     node helios/js_bridge/check_challenge_vectors.js <vectors.json>
 *
 * Reads the fixture generated by the Python implementation and recomputes every
 * challenge with the booth's own JavaScript. Prints a JSON verdict on stdout so
 * the Python test can assert on it precisely rather than scraping text.
 *
 * This is the cheapest possible de-risking of the whole build: an hour of work
 * that removes the failure mode where every ballot verifies locally and every
 * cast fails.
 */

const fs = require('fs');
const {createBoothContext} = require('./booth_context');

function main() {
  const vectorsPath = process.argv[2];
  if (!vectorsPath) {
    console.log(JSON.stringify({ok: false, error: 'no vectors file given'}));
    process.exit(2);
  }

  const vectors = JSON.parse(fs.readFileSync(vectorsPath, 'utf8'));
  const ctx = createBoothContext();

  const results = [];
  let mismatches = 0;

  for (const v of vectors) {
    // Values arrive as decimal strings and go in through the same
    // BigInt.fromJSONObject a deserialized ballot would use.
    const commitments = v.commitments.map(
        (s) => ctx.BigInt.fromJSONObject(s));

    let got;
    try {
      got = ctx.Paillier.disjunctive_challenge_generator(commitments)
                .toJSONObject();
    } catch (e) {
      got = `<threw ${e.message}>`;
    }

    const ok = got === v.challenge;
    if (!ok) mismatches++;
    results.push({label: v.label, expected: v.challenge, got: got, ok: ok});
  }

  // The single-commitment wrapper is exercised separately: §2.8's decryption
  // proof goes through it, and a wrapper that failed to delegate would be
  // invisible to the list-based cases above.
  const single = vectors.find((v) => v.commitments.length === 1);
  let wrapperOk = null;
  if (single) {
    const c = ctx.BigInt.fromJSONObject(single.commitments[0]);
    wrapperOk = ctx.Paillier.fiatshamir_challenge_generator(c).toJSONObject() ===
        single.challenge;
    if (!wrapperOk) mismatches++;
  }

  console.log(JSON.stringify({
    ok: mismatches === 0,
    total: vectors.length,
    mismatches: mismatches,
    fiatshamir_wrapper_ok: wrapperOk,
    results: results,
  }, null, 2));

  process.exit(mismatches === 0 ? 0 : 1);
}

main();
