# Generated by Django 5.2.9 on 2026-09-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0010_add_query_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='crypto_scheme',
            field=models.CharField(choices=[('elgamal', 'Exponential ElGamal'), ('paillier', 'Paillier')], default='elgamal', max_length=20),
        ),
    ]
