# Generated by Django 5.2.9 on 2026-09-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0011_election_crypto_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='paillier_use_crt_proofs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='paillier_use_djn41',
            field=models.BooleanField(default=False),
        ),
    ]
